version: '3'
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nodejs
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    ports:
      - 3000:3000
    command: yarn dev
    networks:
      - default
